name: example
description: An example usage of streamed_items_state_management package.
publish_to: "none"
version: 0.0.1
homepage: https://github.com/KristianBalaj

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1
  tuple: ^2.0.0
  cloud_firestore: ^1.0.1
  streamed_items_state_management:
    git:
      url: https://github.com/cloudis-dev/streamed-items-state-management.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

