include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning

exclude:
  - '**/*.g.dart'
  - '**/*.freezed.dart'
  - '**/**/*generated_plugin*.dart'
  - 'lib/generated/**'
  - 'lib/l10n/**'
  - 'build/**'
  - 'assets/**'

linter:
  rules:
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    avoid_annotating_with_dynamic: false
    avoid_function_literals_in_foreach_calls: false
    prefer_relative_imports: false
    no_default_cases: false
    prefer_mixin: false
    library_private_types_in_public: false
    no_leading_underscores_for_local_identifiers: false
    avoid_print: false