name: streamed_items_state_management
description: State management of items received via stream with updates.
version: 0.0.1
author: Kristián Balaj
homepage: https://github.com/KristianBalaj

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  cloud_firestore: ^0.16.0
  sliver_tools: ^0.1.10+1
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
